version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - 4000:4000
    command: npm start
    container_name: slider-backend

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    command: npm start
    container_name: slider-frontend
    links:
      - backend
